# PBS flags
queue: normal
project: e14
walltime: 05:00:00
ncpus: 1477
mem: 2900GB
jobname: NYFnipo_heat

# Model config
model: mom
shortpath: /short/e14
exe: fms_MOM_SIS_tvvar.x
input:
    - mom025/mask_1920
    - core2nyf2iaf_nipo_trends
    - gfdl_nyf_1080_clean
restart_freq: 1

# Collate:
collate:
     glob: False
     enable: true
     queue: express
     memory: 4GB
     walltime: 05:00:00
     mpi: true
     ncpus: 4
     threads: 2
     flags: -r -v
     exe: /short/public/aph502/mppnccombine-fast
     restart: true

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread -W umask=027
