# PBS flags
queue: normal
project: e14
walltime: 03:00:00
ncpus: 1477
mem: 2900GB
jobname: NYFnipo_heat

collate_walltime: 06:00:00
collate_mem: 12GB
collate_ncpus: 2
collate_queue: express
collate_flags: -n4 -z -m -r
collate_exe: /short/v45/aph502/mom/bin/mppnccombine

# Model config
model: mom
shortpath: /short/e14
input:
    - mom025/mask_1920
    - core2nyf2iaf_nipo_trends
    - gfdl_nyf_1080_clean
collate: true

# Misc
stacksize: unlimited
mpirun: --mca mtl mxm
qsub_flags: -lother=hyperthread
